name: Deploy Automatico Tatame

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Baixando cÃ³digo do GitHub
      uses: actions/checkout@v2

    - name: 2. Conectando e Atualizando Servidor
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "ðŸš€ Iniciando atualizaÃ§Ã£o..."
          
          # Entra na pasta do projeto
          cd /var/www/tatame
          
          # Baixa as novidades e garante que estÃ¡ igual ao GitHub
          git fetch --all
          git reset --hard origin/main
          
          # Instala dependÃªncias
          npm install
          
          # Cria o site (Build)
          npm run build
          
          # Garante permissÃµes
          chown -R www-data:www-data /var/www/tatame
          
          echo "âœ… Site atualizado com sucesso!"